package internal

import (
	"log/slog"

	"github.com/hiveot/hivekit/go/api"
	"github.com/hiveot/hivekit/go/api/msg"
	"github.com/hiveot/hivekit/go/cells"
	"github.com/teris-io/shortid"
)

// The BusFormation is a formation where cells operate in parallel.
//
// This is experimental. The main issue is that members should not forward provided
// requests and notifications to their sink, which is the case for servers but
// not for other cell types. This limits this formation to use with servers.
//
// TODO: Ideally it would work for all cell types.
//
//	option 1: include a switch in cells to disable forwarding of provided notifications/requests
//	option 2: have the bus sink identify and intercept forwarded notif/req
//
// The primary use-case is to group multiple servers for a gateway.
//   - Notifications received by servers from connected services and RC devices
//     are passed to the bus notification sink (not the notification handler).
//   - Notifications passed to the bus HandleNotification function are passed to all
//     bus members (servers). Bus members forward notifications to the remote side.
//     They MUST NOT forward notifications to their own sink as it causes looping.
//   - Requests received by servers from clients are passed to the request sink
//     (not the request handler).
//   - Requests passed to the request handler are passed to each server until
//     one server accepts it. Servers send the request to the matching connected client.
//     Servers MUST NOT forward requests to their request sink as this can cause looping.
//
// Transport Server Members must be fast in identifying if a request is accepted to avoid
// increased latency due to passing a request to each member.
//
// If no cells accept the request then the request fails. It is not passed to the request sink.
//
// Incoming notifications are passed to each bus member in order of definition.
//
// The bus notification sink is registered as the notification sink of each member.
//
// Notifications received or generated by member cells are passed to the bus's
// notification sink (not the handler). Notifications passed to HandleNotification
// are passed to all members. These MUST not be forwarded to the notification sink.
type BusFormation struct {
	cells.HiveCellBase
	// cells in the order to instantiate and link
	modDefs []api.CellDefinition `yaml:"star"`

	// cell instances by their ThingID
	instances map[string]api.IHiveCell

	// The factory to use
	f api.ICellFactory
}

// Pass notifications to bus members and up the notification chain.
// bus members are set to not forward notifications.
func (r *BusFormation) HandleNotification(notif *msg.NotificationMessage) {
	for _, member := range r.instances {
		// members are configured to not forward notifications
		member.HandleNotification(notif)
	}
	r.ForwardNotification(notif)
}

// Requests sent to the bus are passed to each cell until it succeeds.
// bus members are set to not forward unhandled requests.
// If no cells succeed then forward it down the chain.
func (r *BusFormation) HandleRequest(req *msg.RequestMessage, replyTo msg.ResponseHandler) error {
	var err error
	for _, member := range r.instances {
		err = member.HandleRequest(req, replyTo)
		if err == nil {
			// request was handled by a group member
			return nil
		}
	}
	return r.ForwardRequest(req, replyTo)
}

// Start the bus formation.
// Note: Link before Start. Start must only be called after the bus has its notification
// sink set as this sink is passed to the members for their notification sink.
// Future: Use a helper cell or use separate handlers for emitted vs forwarded notifications.
func (r *BusFormation) Start() error {

	// add the cell definitions to the factory
	if r.modDefs != nil {
		// register all cells
		for _, modDef := range r.modDefs {
			r.f.RegisterCell(modDef)
		}
	}
	// start cells in the defined order
	for _, cellDef := range r.modDefs {
		member, err := r.f.StartCell(cellDef.Type, true)
		// cell cant be started. This is not fatal
		if err != nil {
			slog.Error("BusRecipe: starting cell failed. Not fatal but this might not work as expected",
				"cellType", cellDef.Type, "err", err.Error())
			// m.Stop()
			// return err
		} else if member == nil {
			// don't track 'one-shot' cells that are used to initialize the factory.
			// These return nil without error.
		} else {
			r.instances[member.GetThingID()] = member
		}
		// Members MUST not forward unhandled requests otherwise the same request
		// can arrive multiple times, one for each member. This currently only works for servers
		// as per specification they send requests to remote clients or ignore them.
		member.SetForwarding(false, false)

		// pass member notifications directly to the bus notification sink
		// note this requires that the bus has a sink set before starting it.
		// possible improvement is to create a helper sink instead that forwards it.
		// member.SetNotificationSink(r.handleMemberNotification)
		busNotifSink := r.GetNotificationSink()
		member.SetNotificationSink(busNotifSink)

		// similarly, set the member request sink to the bus request sink. link before start.
		// Thus, requests emitted by members are passed to the bus request sink.
		//
		busReqSink := r.GetRequestSink()
		member.SetRequestSink(busReqSink)
		_, isServer := member.(api.ITransportServer)
		if !isServer {
			slog.Error("Start: Bus members must be a transport server, otherwise "+
				"requests/notifications multiply",
				"memberID", member.GetThingID())
		}
	}
	return nil
}

// Create a new bus formation with an array of cells
func NewBusFormation(modDefs []api.CellDefinition) *BusFormation {
	thingID := "BusRecipe-" + shortid.MustGenerate()
	r := &BusFormation{
		HiveCellBase: *cells.NewHiveCellBase(thingID, 0),
		modDefs:      modDefs,
	}
	var _ api.IHiveCell = r // api check
	return r
}
