package grpcclient

import (
	"context"
	"errors"
	"io"
	"log/slog"
	"sync/atomic"
	"time"

	grpcapi "github.com/hiveot/hivekit/go/modules/transports/grpc/api"
)

const ServiceMsgChanSize = 30

// GrpcBufferedStream for receiving and sending messages on a GRPC stream connection.
// Use Run to start processing incoming messages.
type GrpcBufferedStream struct {

	// this channel is used to signal the read/write loops to exit
	cancelChan chan struct{}

	isConnected atomic.Bool
	grpcStream  grpcapi.IGrpcMessageStream

	// how long to wait for a response after sending a request
	sendTimeout time.Duration

	// the send channel with buffer to force sequential sending
	sendChan chan *grpcapi.GrpcMsg
}

// when the client disconnects, we want to make sure that the read loop exits gracefully and that all pending response handlers are notified of the disconnection. This is done by cancelling the stream context, which should cause the read loop to exit with a context.Canceled error. The response handlers will then be notified of the disconnection and can handle it accordingly.
func (bs *GrpcBufferedStream) cancelSafely() {
	if !bs.isConnected.Load() {
		return
	}
	bs.isConnected.Store(false)
	close(bs.cancelChan)
}

// Start Processing a message stream from the client.
// This returns when the stream is closed.
func (bs *GrpcBufferedStream) recvLoop(recvHandler func(msgType string, jsonRaw string)) {
	// see also https://stackoverflow.com/questions/46933538/how-to-close-grpc-stream-for-server
	for {
		if !bs.isConnected.Load() {
			break
		}
		result, err := bs.grpcStream.Recv()
		if err == io.EOF {
			slog.Info("service recvLoop: grpc stream read loop closed due to EOF")
			break
		} else if errors.Is(err, context.Canceled) {
			slog.Info("service recvLoop: Graceful shutdown")
			break
		} else if err != nil {
			slog.Warn("service recvLoop: Recv error", "err", err.Error())
			break
		}
		slog.Info("service recvLoop: received message:" + result.MsgType)
		// parent handles flow control
		recvHandler(result.MsgType, result.JsonPayload)
	}
	slog.Info("service recvLoop: recvLoop ended")

	//end the blocking in WaitUntilDisconnect
	bs.cancelSafely()
}

// Send a stream message to the remote client
func (bs *GrpcBufferedStream) Send(msgType, jsonPayload string) (err error) {
	grpcMsg := &grpcapi.GrpcMsg{
		MsgType:     msgType,
		JsonPayload: jsonPayload,
	}
	// if the send channel is full, allow a wait before disconnecting the client.
	ctx, cancelFn := context.WithTimeout(context.Background(), bs.sendTimeout)
	defer cancelFn()
	select {
	case bs.sendChan <- grpcMsg:
		// all is well
		err = nil
	case <-ctx.Done():
		err = ctx.Err()
	default:
		slog.Info("service Send: channel is full. Closing the connection.", "err", err.Error())
		// send channel is full the client is too slow -- disconnect it
		bs.cancelSafely()
		err = grpcapi.ErrClientTooSlow
	}
	cancelFn()
	return err
}

// Send loop using the send channel to ensure sequential delivery of messages.
// grpc streams do not support concurrent sending.
func (bs *GrpcBufferedStream) sendLoop() {
	for msg := range bs.sendChan {
		slog.Info("service sendLoop: sending message:" + msg.MsgType)
		if err := bs.grpcStream.Send(msg); err != nil {
			break
		}
	}
	slog.Info("service sendLoop: sendLoop ended")
	// bs.cancelSafely() // in	case client disconnected
}

// Close the stream connection
func (bs *GrpcBufferedStream) Close() {
	bs.cancelSafely()
}

// // IsConnected returns the current connection status
func (sc *GrpcBufferedStream) IsConnected() bool {
	return sc.isConnected.Load()
}

// WaitUntilDisconnect waits until the send or receive stream is closed.
// Intended to be called by the (server) serve handler to avoid the stream from
// closing on return.
func (bs *GrpcBufferedStream) WaitUntilDisconnect() {
	<-(bs.cancelChan)
	bs.isConnected.Store(false)
}

// NewGrpcBufferedStream creates a concurrently safe buffered instance from a grpc stream.
//
// The resulting instance supports concurrent sending and receiving of messages.
// This supports sending messages concurrently.
// If the send buffer is full, the client is considered too slow and the stream is closed
// after waiting the sendTimeout duration for the buffer to be available.
//
// Call WaitUntilDisconnect() after creating this instance to wait until the stream
// is closed by the client or the server. Needed by the server serve handler.
//
//	grpcStream is the raw GRPC stream (currently generated by protobuf)
//	recvHandler is called when a new message is received from the stream.
//	sendTimeout is the default timeout for sending messages on this stream
//	 when the send buffer is full.
func NewGrpcBufferedStream(
	grpcStream grpcapi.IGrpcMessageStream,
	recvHandler func(msgType string, jsonRaw string),
	sendTimeout time.Duration,
) *GrpcBufferedStream {
	strm := &GrpcBufferedStream{
		sendTimeout: sendTimeout,
		grpcStream:  grpcStream,
		// ServiceMsgChanSize is the default buffer size. TODO:flow control
		sendChan:   make(chan *grpcapi.GrpcMsg, ServiceMsgChanSize),
		cancelChan: make(chan struct{}),
	}
	strm.isConnected.Store(true)
	go strm.recvLoop(recvHandler)
	go strm.sendLoop()

	// peerInfo, ok := peer.FromContext(grpcStream.Context())
	// var remoteAddr string
	// if ok {
	// 	remoteAddr = peerInfo.Addr.String()
	// }
	return strm
}
