# Makefile for building examples
DIST_FOLDER=./dist

.FORCE: 

example1: .FORCE
	go build -o $(DIST_FOLDER)/$@ $@/main.go

example2: .FORCE
	go build -o $(DIST_FOLDER)/$@ $@/main.go

example3: .FORCE
	go build -o $(DIST_FOLDER)/$@ $@/main.go

