package modules

import "github.com/hiveot/hivekit/go/modules/messaging"

// The golang pipeline module interface  (proposed)
//
// The module is responsesible for creating the optional TM, receive requests and
// sending notifications.
type IHiveModule interface {

	// AddSink sets the destination sink to forward messages to, to send the processing result to, or both.
	// Modules can support a single or multiple sinks. If no more sinks can be added an error is returned.
	// AddSink can be invoked before or after start is called.
	AddSink(sink IHiveModule) error

	// GetGetTMTD returns the module's Thing Model describing its properties, actions and events.
	// If no TD is supported then this returns nil.
	// Forms in the TD are typically added by the pipeline messaging server.
	GetTM() string

	// HandleNotification processes or forwards an SME notification message. This is
	// an input to the module.
	//
	// In transport modules HandleNotification sends the notification to connected
	// clients that have subscribed to the notification.
	//
	// Notifications generated by the module itself, or received in transport modules,
	// should be passed to the sinks and not processed in HandleNotification.
	HandleNotification(notif *messaging.NotificationMessage)

	// HandleRequest processes a request for the module or forward it to a sink. This
	// is an input to the module.
	//
	// If the request is not addressed to the module then the request is forwarded to
	// the sinks to enable daisy chaining modules.
	//
	// This returns an SME response containing the delivery status and processing result.
	//
	// In transport modules, If the request has a ThingID of a connected client then
	// it is forwarded to that client. This is most likely the case when the client is
	// an IoT device using connection reversal.
	//
	// In transport modules if the request is intended for the transport module itself
	// the module will process it like any other module would. Eg access properties
	// or invoke actions, assuming the module has those defined.
	//
	// In transport modules, when a request message is received from a remote client
	// and is intended for the transport module, it is passed to the sink and not
	// processed untile the sink passes it to the modules HandleRequest method.
	//
	HandleRequest(request *messaging.RequestMessage) *messaging.ResponseMessage

	// Start readies the module for use
	Start() error

	// Stop halts module operation and releases resources.
	Stop()
}
