package modules

import (
	"github.com/hiveot/hivekit/go/msg"
)

// The HiveOT module interface  (proposed)
//
// What is a module?
//   - a module performs a task
//   - a module is identified with a Module ID
//   - modules receive requests and return responses to the replyTo addres
//   - modules return responses
//   - modules send notifications
//   - modules are a component of an IoT device or its consumer
//   - modules can be a Thing itself and have a TM that describes it
//   - one or more modules reside on a device  - the device address is added to its TD
//   - devices have a URI they can be reached at
//   - to send reach a module
//
// Consumers do not connect directly to modules, instead they connect to the device,
// which forwards messages to the module running on it. The device protocol server
// is a module itself.
type IHiveModule interface {
	// GetModuleID returns module's ID.
	// For agents/devices this is the ThingID, for consumers this is the clientID.
	GetModuleID() string

	// GetTM returns the module's Thing Model JSON document, describing its properties, actions and events.
	// If no TM is supported then this returns nil.
	// Forms in the TD are typically added by the protocol server.
	GetTM() string

	// HandleNotification processes or forwards a notification message. This is
	// an input to the module.
	//
	// Notifications generated by the module itself, or received in transport modules,
	// should be passed to the sinks and not processed in HandleNotification.
	HandleNotification(notif *msg.NotificationMessage)

	// HandleRequest passes a request to the module for processing.
	// This is an input to the module which behaves as follows:
	//
	// A: If the request is addressed to the module based on its ThingID:
	// If the module processes the request synchronously then it invokes replyTo with the response
	// before returning.
	// If the module processing the request asynchronously then this invokes replyTo with the response
	// after returning.
	//
	// B: If a module does not recognize the request ThingID then the request is
	// forwarded to the registered sink's HandleRequest method.
	//
	// C: If a module needs to process or validate the request, it can do so and forward
	// it onwards to the next sink in the chain or cancel it with an error response.
	//
	// D: If a module forwards the request and needs to process the response it must
	// set the replyTo to its own handler. This handler then forwards the response
	// to the original replyTo endpoint.
	//
	// An error is returned if the request cannot processed, forwarded and is discarded.
	HandleRequest(request *msg.RequestMessage, replyTo msg.ResponseHandler) error

	// HandleResponse processes an asynchronous response for the module.
	//
	// This is the return path after the module's request has yielded a response.
	// The message flow is similar to that of a request, in that the response is forwarded
	// along the chain of sinks until it reaches the destined module.
	//
	// This returns nil if the response is accepted, or this returns an error if
	// the response is not accepted (eg, lost).
	HandleResponse(resp *msg.ResponseMessage) error

	// SetSink sets the destination sink to forward messages to, to send the processing result to, or both.
	// If a sink is already set it is overwritten.
	// This is optional, if not sink is set then the module is the end of the line.
	// SetSink can be invoked before or after start is called.
	// SetSink(sink IHiveModule)

	// Start readies the module for use.
	// Intended for modulues to initialize resources
	Start() error

	// Stop halts module operation and releases resources.
	// Intended for modulues to free resources
	Stop()
}

// A module sink is the destination for messages from a module.
// This allows to create a sink as needed.
// This implements the IHiveModule interface with empty methods.
// type ModuleSink struct {
// 	Sink               IHiveModule
// 	ModuleID           string
// 	HandleResponse     msg.ResponseHandler
// 	HandleRequest      msg.RequestHandler
// 	HandleNotification msg.NotificationHandler
// }

// func (m *ModuleSink) GetModuleID() string      { return m.ModuleID }
// func (m *ModuleSink) SetSink(sink IHiveModule) { m.Sink = sink }
// func (m *ModuleSink) Start() error             { return nil }
// func (m *ModuleSink) Stop()
// func (m *ModuleSink) GetTM() string { return "" }
