package internal

import (
	"fmt"
	"log/slog"

	"github.com/hiveot/hivekit/go/api"
	"github.com/hiveot/hivekit/go/api/msg"
	"github.com/hiveot/hivekit/go/cells"
	"github.com/teris-io/shortid"
)

// The BusFormation is a formation where cells operate in parallel.
//
// Requests are passed to each member in turn until one accepts. It is
// intended for cells that can handle requests for multiple things.
//
// Flow:
//  1. req -> bus -> [all members until one accepts]
//  2. notif -> bus -> [all members] (no forwarding)
//  3. [members] notif -> bus notification sink
//  4. [members] req -> bus request sink
//
// The primary use-case is to group multiple servers for a gateway.
//   - Notifications received by servers from connected services and RC devices
//     are passed to the bus notification sink (not the notification handler).
//   - Notifications passed to the bus HandleNotification function are passed to all
//     bus members (servers). Bus members forward notifications to the remote side.
//     They MUST NOT forward notifications to their own sink as it causes looping.
//   - Requests received by servers from clients are passed to the request sink
//     (not the request handler).
//   - Requests passed to the request handler are passed to each server until
//     one server accepts it. Servers send the request to the matching connected client.
//     Servers MUST NOT forward requests to their request sink as this can cause looping.
//
// Transport Server Members must be fast in identifying if a request is accepted to avoid
// increased latency due to passing a request to each member.
//
// If no cells accept the request then the request fails. It is not passed to the request sink.
//
// Incoming notifications are passed to each bus member in order of definition.
//
// The bus notification sink is registered as the notification sink of each member.
//
// Notifications received or generated by member cells are passed to the bus's
// notification sink (not the handler). Notifications passed to HandleNotification
// are passed to all members. These MUST not be forwarded to the notification sink.
type BusFormation struct {
	cells.HiveCellBase
	// cells in the order to instantiate and link
	cellDefs []api.CellDefinition `yaml:"star"`

	// members of the bus
	members []api.IHiveCell

	// The factory to use
	f api.ICellFactory
}

// Pass notifications to bus members and up the notification chain.
// bus members are set to not forward notifications.
func (r *BusFormation) HandleNotification(notif *msg.NotificationMessage) {
	for _, member := range r.members {
		// members are configured to not forward notifications
		member.HandleNotification(notif)
	}
	r.ForwardNotification(notif)
}

// Requests sent to the bus are passed to each cell until it succeeds.
// bus members are set to not forward unhandled requests.
// If no cells succeed then forward it down the chain.
func (r *BusFormation) HandleRequest(req *msg.RequestMessage, replyTo msg.ResponseHandler) error {
	var err error
	for _, member := range r.members {
		err = member.HandleRequest(req, replyTo)
		if err == nil {
			// request was handled by a group member
			return nil
		}
	}
	return r.ForwardRequest(req, replyTo)
}

// Update the member's sink for notifications from the formation.
func (r *BusFormation) SetNotificationSink(sink api.IHiveCell, thingIDs ...string) {
	for _, member := range r.members {
		member.SetNotificationSink(sink, thingIDs...)
	}
	r.HiveCellBase.SetNotificationSink(sink, thingIDs...)
}

// Set the sink for requests from the bus
func (r *BusFormation) SetRequestSink(sink api.IHiveCell) {
	for _, member := range r.members {
		member.SetRequestSink(sink)
	}
	r.HiveCellBase.SetRequestSink(sink)
}

// Set a named slot in the bus formation
func (r *BusFormation) SetSlot(slotID string, modDef api.CellDefinition) error {
	return fmt.Errorf("todo")
}

// NewBusFormation returns a ready-to-use bus formation for running cells in parallel.
//
// This disables forwarding on the bus members to prevent multiple requests and
// notifications to be passed to the bus sinks.
//
// Call Start() on the factory to activate autonomous processes and publications.
//
// Use SetNotificationSink and SetRequestSink before calling Start on the factory.
//
// If a cell fail to be created then this continues without the failed cell.
func NewBusFormation(
	f api.ICellFactory, cellDefs []api.CellDefinition) (*BusFormation, error) {
	thingID := "NewBusFormation-" + shortid.MustGenerate()

	bus := &BusFormation{
		HiveCellBase: *cells.NewHiveCellBase(thingID),
		f:            f,
		cellDefs:     cellDefs,
		members:      make([]api.IHiveCell, 0, len(cellDefs)),
	}
	bus.SetTimeout(f.GetEnvironment().RpcTimeout)

	// add the cell definitions to the factory
	if bus.cellDefs != nil {
		// register all cells
		for _, modDef := range bus.cellDefs {
			bus.f.RegisterCell(modDef)
		}
	}
	// create and link cells in the defined order
	for _, cellDef := range bus.cellDefs {
		member, err := bus.f.NewCell(cellDef.Type, true)
		// cell cant be created. This is not fatal in a bus.
		if err != nil {
			slog.Error("NewBusFormation: creating cell failed. Not fatal but this might not work as expected",
				"cellType", cellDef.Type, "err", err.Error())
			// m.Stop()
			// return err
		} else if member == nil {
			// don't track 'one-shot' cells that are used to initialize the factory.
			// These return nil without error.
		} else {
			bus.members = append(bus.members, member)
			// Members MUST not forward unhandled requests otherwise the same request
			// can arrive multiple times, one for each member. Similarly, members should
			// not forward notifications otherwise the same notification will be forwarded
			// multiple times.
			member.SetForwarding(false, false)
		}
	}

	var _ api.IHiveCell = bus // api check
	return bus, nil
}
