package msg

import (
	"github.com/hiveot/hivekit/go/utils"
	"github.com/teris-io/shortid"
)

// NotificationHandler handles a notification, send by an agent.
//
// msg is the notification
type NotificationHandler func(msg *NotificationMessage)

// ResponseMessage, ActionStatus and ThingValue define the standardized messaging
// envelopes for handling responses.
// Each transport protocol bindings map this format to this specific format.

// MessageTypeNotification identify the message as a notification.
const MessageTypeNotification = "notification"

// NotificationMessage for sending asynchronous notifications to a subscriber/observer
//
// The Data field contains the message response data as defined by the operation
type NotificationMessage struct {

	// AffordanceType identifies the type of affordance that name points to
	// eg AffordanceTypeProperty or AffordanceTypeEvent
	AffordanceType AffordanceType `json:"affordanceType"`

	// CorrelationID of the request this is a response to, if any.
	CorrelationID string `json:"correlationID,omitempty"`

	// Data containing the notification data as described in the TD event or property dataschema.
	Data any `json:"value"` // native

	// MessageID optional unique ID of the message. Intended to detect duplicates.
	// Generated by the protocol binding.
	MessageID string `json:"messageID,omitempty"`

	// Name of the event or property affordance this is a notification for.
	// This field is required
	Name string `json:"name"`

	// Authenticated ID of the agent sending the notification, set by the server.
	// The protocol server MUST set this to the authenticated sender.
	SenderID string `json:"senderID"`

	// ThingID of the thing this is a notification from.
	ThingID string `json:"thingID"`

	// Timestamp the notification was created
	Timestamp string `json:"timestamp,omitempty"`
}

// ToString is a helper to easily read the notification data as a string
func (notif *NotificationMessage) ToString(maxlen int) string {
	return utils.DecodeAsString(notif.Data, maxlen)
}

// NewNotificationMessage creates a new NotificationMessage instance.
//
//	senderID is the agent sending the notification
//	affordanceType is the Thing affordance type, eg property or event
//	thingID is the thing the value applies to (destination of action or source of event)
//	name is the name of the property, event or action affordance as described in the thing TD
//	data is the data as defined in the corresponding affordance dataschema or nil if not applicable
func NewNotificationMessage(
	senderID string, affordanceType AffordanceType, thingID, name string, data any) *NotificationMessage {
	notif := &NotificationMessage{
		AffordanceType: affordanceType,
		SenderID:       senderID,
		ThingID:        thingID,
		Name:           name,
		Data:           data,
		Timestamp:      utils.FormatNowUTCMilli(),
		MessageID:      shortid.MustGenerate(),
	}
	return notif
}
