package msg

import (
	"time"

	"github.com/hiveot/hivekit/go/utils"
	"github.com/teris-io/shortid"
)

// MessageTypeResponse identify the message as a response.
const MessageTypeResponse = "response"

// ResponseHandler handles an asynchronous response to a request, send by an agent.
// The handler delivers the response to the client that sent the original request.
//
// This returns an error if the response cannot be delivered. This can be used to
// retry sending the response at a later time.
type ResponseHandler func(msg *ResponseMessage) error

// Request status provided with the response.
// this aligns with action status values from WoT spec
const (
	// StatusPending - the request has not yet been delivered
	StatusPending = "pending"
	// StatusRunning - the request is being processed
	StatusRunning = "running"
	// StatusCompleted - the request processing was completed
	StatusCompleted = "completed"
	// StatusFailed - the request processing or delivery failed
	StatusFailed = "failed"
)

// ResponseMessage serves to notify a client of the result of a request.
//
// The Value field contains the message response data as defined by the TD output.
//
// Action related response output:
//   - invokeaction             action output as per TD, when status==completed
//   - queryaction              ResponseMessage with latest result from the action
//   - queryallactions          map [affordanceName]ResponseMessage objects
//
// Property related response output:
//   - readproperty             ThingValue object
//   - readallproperties        map[name]ThingValue objects
//
// Event related response output
//   - readevent                ThingValue object
//   - readallevents            map[name]ThingValue objects
type ResponseMessage struct {

	// Authenticated clientID of the agent sending the response.
	//
	// This is set by the transport server handling the request.
	// When using reverse connection, the transport server sets this to the clientID of
	// the agent that sends the response.
	//
	// This feature of hiveot enables tracking of which service instance responded to a
	// request. See also ConsumerID
	//
	// The Hub protocol server MUST set this to the authenticated sender.
	AgentID string `json:"agentID"`

	// CorrelationID of the request this is a response to, if any.
	// CorrelationID can be required for a response to find its way back to the client
	// sending the request.
	CorrelationID string `json:"correlationID,omitempty"`

	// ConsumerID holds the authenticated ID of the consumer that sent the request.
	// This is a hiveot feature supported by the transport servers.
	//
	// Intended for tracking which user sent the request that led to this response.
	// It can be viewed in the result of 'queryaction', if supported by the server
	// connection.
	ConsumerID string `json:"consumerID"`

	// Error contains the short error description when status is failed.
	// Matches RFC9457 https://www.rfc-editor.org/rfc/rfc9457
	Error *ErrorValue `json:"error"`

	// The input to the request. This is included for historical purposes.
	// This only populated when the response is sent by supporting devices. The
	// transport servers can attempt to fill this in if supported.
	Input any `json:"input,omitempty"`

	// MessageID unique ID of the message. Intended to detect duplicates.
	// Generated by the protocol binding.
	MessageID string `json:"messageID,omitempty"`

	// MessageType identifies this message payload as a response
	// This is set to the value of MessageTypeResponse
	MessageType string `json:"messageType"`

	// Name of the action or property affordance this is a response from.
	Name string `json:"name"`

	// The operation this is a response to. This MUST be the operation provided in the request.
	Operation string `json:"operation"`

	// Output of the request as described in the TD affordance output or value dataschema.
	//
	// If the operation is one of the Thing level operations, the value is specified
	// by the operation's dataschema or empty if none is specified.
	//
	// In response to actions this is the output dataschema from the action affordance,
	// or empty if the output dataschema is not specified in the TD.
	//
	// In response to a write request this is the last known value.
	//
	// Note that different protocol bindings use a different field depending on the operation.
	// The message converter stores the response value(s) into the Value field.
	//
	// If an error is returned then value is empty
	Output any `json:"output,omitempty"`

	// State of request with progress: pending, running, completed, failed.
	// In most cases there is only a single response to a request. This should not be
	// relied on however.
	// In case of long running requests this has state running (or pending). The HiveOT
	// convention is to sent state changes due to actions as events with the action name, and
	// state changes due to property writes as property update notifications
	State string `json:"state,omitempty"`

	// ThingID of the thing this is a response from.
	// For responses passed to consumers this is the digitwin dThingID
	// For responses sent by agents this is the agent ThingID
	// This field is optional and intended to help debugging and logging.
	ThingID string `json:"thingID,omitempty"`

	// Timestamp the response was created
	Timestamp string `json:"timestamp,omitempty"`
}

// AsError returns the error, or nil if the response does not contain an error
// This also returns nil if response itself is nil
func (resp *ResponseMessage) AsError() error {
	if resp != nil && resp.Error != nil {
		return resp.Error.AsError()
	}
	return nil
}

// ToString is a convenience function for converting the value to text
// intended for logging
func (resp *ResponseMessage) ToString(maxlen int) (valueStr string) {
	return utils.DecodeAsString(resp.Output, maxlen)
}

// Decode the value in the response
// If the response contains an error, then this error is returned.
func (resp *ResponseMessage) Decode(output any) error {
	if resp != nil && resp.Error != nil {
		return resp.Error.AsError()
	}
	err := utils.Decode(resp.Output, output)
	return err
}

// NewResponseMessage creates a new ResponseMessage instance.
//
// This sets status to completed if err is nil or Failed if err is provided.
// If the status is not completed or failed then set it to the appropriate value after creation.
//
//	operation is the request operation WoTOp... or HTOp...
//	thingID is the thing the value applies to (destination of action or source of event)
//	name is the name of the property, event or action affordance as described in the thing TD
//	output is the response data as defined in the corresponding affordance dataschema or nil if not applicable
//	err is the optional error response which will set status to bad request
//	state is the optional status. Defaults to completed or failed in case of error
//	correlationID  ID provided by the request
func NewResponseMessage(
	operation string, thingID, name string, output any, err error, state string, correlationID string) *ResponseMessage {

	if state == "" {
		state = StatusCompleted
		if err != nil {
			state = StatusFailed
		}
	}
	resp := &ResponseMessage{
		CorrelationID: correlationID,
		Error:         ErrorValueFromError(err),
		MessageID:     shortid.MustGenerate(),
		MessageType:   MessageTypeResponse,
		Name:          name,
		Output:        output,
		Operation:     operation,
		State:         state,
		Timestamp:     utils.FormatUTCMilli(time.Now()),
		ThingID:       thingID,
	}
	return resp
}
