// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcServiceClient is the client API for GrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcServiceClient interface {
	// ping to test connectivity
	Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsg, error)
	// bi-directional message stream between client and server
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	MsgStream(ctx context.Context, opts ...grpc.CallOption) (GrpcService_MsgStreamClient, error)
}

type grpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcServiceClient(cc grpc.ClientConnInterface) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsg, error) {
	out := new(PingMsg)
	err := c.cc.Invoke(ctx, "/grpcapi.GrpcService/ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) MsgStream(ctx context.Context, opts ...grpc.CallOption) (GrpcService_MsgStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcService_ServiceDesc.Streams[0], "/grpcapi.GrpcService/MsgStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcServiceMsgStreamClient{stream}
	return x, nil
}

type GrpcService_MsgStreamClient interface {
	Send(*GrpcMsg) error
	Recv() (*GrpcMsg, error)
	grpc.ClientStream
}

type grpcServiceMsgStreamClient struct {
	grpc.ClientStream
}

func (x *grpcServiceMsgStreamClient) Send(m *GrpcMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcServiceMsgStreamClient) Recv() (*GrpcMsg, error) {
	m := new(GrpcMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcServiceServer is the server API for GrpcService service.
// All implementations must embed UnimplementedGrpcServiceServer
// for forward compatibility
type GrpcServiceServer interface {
	// ping to test connectivity
	Ping(context.Context, *PingMsg) (*PingMsg, error)
	// bi-directional message stream between client and server
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	MsgStream(GrpcService_MsgStreamServer) error
	mustEmbedUnimplementedGrpcServiceServer()
}

// UnimplementedGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcServiceServer struct {
}

func (UnimplementedGrpcServiceServer) Ping(context.Context, *PingMsg) (*PingMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGrpcServiceServer) MsgStream(GrpcService_MsgStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MsgStream not implemented")
}
func (UnimplementedGrpcServiceServer) mustEmbedUnimplementedGrpcServiceServer() {}

// UnsafeGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServiceServer will
// result in compilation errors.
type UnsafeGrpcServiceServer interface {
	mustEmbedUnimplementedGrpcServiceServer()
}

func RegisterGrpcServiceServer(s grpc.ServiceRegistrar, srv GrpcServiceServer) {
	s.RegisterService(&GrpcService_ServiceDesc, srv)
}

func _GrpcService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.GrpcService/ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).Ping(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_MsgStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServiceServer).MsgStream(&grpcServiceMsgStreamServer{stream})
}

type GrpcService_MsgStreamServer interface {
	Send(*GrpcMsg) error
	Recv() (*GrpcMsg, error)
	grpc.ServerStream
}

type grpcServiceMsgStreamServer struct {
	grpc.ServerStream
}

func (x *grpcServiceMsgStreamServer) Send(m *GrpcMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcServiceMsgStreamServer) Recv() (*GrpcMsg, error) {
	m := new(GrpcMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcService_ServiceDesc is the grpc.ServiceDesc for GrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _GrpcService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MsgStream",
			Handler:       _GrpcService_MsgStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_transport.proto",
}
