// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: grpc_transport.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType     string `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	JsonPayload string `protobuf:"bytes,2,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
}

func (x *GrpcMsg) Reset() {
	*x = GrpcMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_transport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMsg) ProtoMessage() {}

func (x *GrpcMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_transport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMsg.ProtoReflect.Descriptor instead.
func (*GrpcMsg) Descriptor() ([]byte, []int) {
	return file_grpc_transport_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcMsg) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *GrpcMsg) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

type PingRespMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PingRespMsg) Reset() {
	*x = PingRespMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_transport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRespMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRespMsg) ProtoMessage() {}

func (x *PingRespMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_transport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRespMsg.ProtoReflect.Descriptor instead.
func (*PingRespMsg) Descriptor() ([]byte, []int) {
	return file_grpc_transport_proto_rawDescGZIP(), []int{1}
}

func (x *PingRespMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_grpc_transport_proto protoreflect.FileDescriptor

var file_grpc_transport_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x07,
	0x47, 0x72, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x4d,
	0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x78, 0x0a, 0x0b, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x09, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68,
	0x69, 0x76, 0x65, 0x6f, 0x74, 0x2f, 0x68, 0x69, 0x76, 0x65, 0x6b, 0x69, 0x74, 0x2f, 0x67, 0x6f,
	0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_transport_proto_rawDescOnce sync.Once
	file_grpc_transport_proto_rawDescData = file_grpc_transport_proto_rawDesc
)

func file_grpc_transport_proto_rawDescGZIP() []byte {
	file_grpc_transport_proto_rawDescOnce.Do(func() {
		file_grpc_transport_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_transport_proto_rawDescData)
	})
	return file_grpc_transport_proto_rawDescData
}

var file_grpc_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_transport_proto_goTypes = []interface{}{
	(*GrpcMsg)(nil),       // 0: grpcapi.GrpcMsg
	(*PingRespMsg)(nil),   // 1: grpcapi.PingRespMsg
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_grpc_transport_proto_depIdxs = []int32{
	2, // 0: grpcapi.GrpcService.ping:input_type -> google.protobuf.Empty
	0, // 1: grpcapi.GrpcService.MsgStream:input_type -> grpcapi.GrpcMsg
	1, // 2: grpcapi.GrpcService.ping:output_type -> grpcapi.PingRespMsg
	0, // 3: grpcapi.GrpcService.MsgStream:output_type -> grpcapi.GrpcMsg
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_transport_proto_init() }
func file_grpc_transport_proto_init() {
	if File_grpc_transport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_transport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_transport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRespMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_transport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_transport_proto_goTypes,
		DependencyIndexes: file_grpc_transport_proto_depIdxs,
		MessageInfos:      file_grpc_transport_proto_msgTypes,
	}.Build()
	File_grpc_transport_proto = out.File
	file_grpc_transport_proto_rawDesc = nil
	file_grpc_transport_proto_goTypes = nil
	file_grpc_transport_proto_depIdxs = nil
}
