package digitwin_test

import (
	"fmt"
	"log/slog"
	"os"
	"strings"
	"testing"

	"github.com/hiveot/hivekit/go/modules/digitwin"
	digitwinapi "github.com/hiveot/hivekit/go/modules/digitwin/api"
	"github.com/hiveot/hivekit/go/modules/digitwin/internal/module"
	"github.com/hiveot/hivekit/go/modules/directory"
	directoryapi "github.com/hiveot/hivekit/go/modules/directory/api"
	"github.com/hiveot/hivekit/go/modules/transports"
	"github.com/hiveot/hivekit/go/modules/transports/tptests"
	"github.com/hiveot/hivekit/go/modules/transports/wss"
	"github.com/hiveot/hivekit/go/msg"
	"github.com/hiveot/hivekit/go/utils"
	"github.com/hiveot/hivekit/go/wot"
	"github.com/hiveot/hivekit/go/wot/td"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var storageRoot = ""

// TestMain setup logging and creates a test environment
func TestMain(m *testing.M) {
	utils.SetLogging("info", "")

	result := m.Run()
	if result != 0 {
		println("Test failed with code:", result)
	} else {
	}

	os.Exit(result)
}

// startService initializes a service and a client
// This doesn't use any transport.
func startService() (
	testEnv *tptests.TestEnv,
	dir directoryapi.IDirectoryServer,
	dtw digitwinapi.IDigitwinModule,
	stopFn func()) {

	// testEnv,cancelFn = tptests.StartTestEnv(transports.ProtocolSchemeWotWSS)
	testEnv = tptests.NewTestEnv()
	// http server needed for all communications
	testEnv.StartHttpServer()
	// a test server for websocket communication
	appServer := testEnv.StartTestServer(transports.ProtocolSchemeWotWSS)

	dir = directory.NewDirectoryServer("", testEnv.HttpServer)
	err := dir.Start("")
	if err != nil {
		panic("Failed to start directory server")
	}

	dtw = digitwin.NewDigitwinModule(storageRoot, dir, appServer.AddTDForms)
	err = dtw.Start("")
	if err != nil {
		panic("unable to start the digitwin service")
	}

	// create a pipeline consisting of the server, directory, and digital twin:
	// the directory and digitwin modules receive requests sent to the server
	appServer.SetRequestSink(dir.HandleRequest)
	dir.SetRequestSink(dtw.HandleRequest)
	// notifications from the directory and digitwin modules go to the server who forwards it to subscribers
	dir.SetNotificationSink(appServer.HandleNotification)
	dtw.SetNotificationSink(appServer.HandleNotification)
	// notifications from the server are sent by agents with reverse connections
	// these are passed to the digital twin to update the digitwin state
	appServer.SetNotificationSink(dtw.HandleNotification)

	slog.Info("--- digitwin test environment started ---")

	return testEnv, dir, dtw, func() {
		dir.Stop()
		dtw.Stop()
		testEnv.Server.Stop()
		testEnv.HttpServer.Stop()
	}
}
func TestStartStop(t *testing.T) {
	t.Logf("---%s---\n", t.Name())

	testEnv, dir, dtw, stopFn := startService()
	defer stopFn()
	_ = testEnv
	_ = dir
	_ = dtw
}

// Write a TD to the directory and verify a digital twin is created using the module API
func TestCreateDigitwinTD(t *testing.T) {
	t.Logf("---%s---\n", t.Name())
	const agentID = "agent1"

	testEnv, dir, dtw, stopFn := startService()
	defer stopFn()

	// pretent to be an agent that writes a TD to the directory
	td1 := testEnv.CreateTestTD(0)
	td1Json, _ := td.MarshalTD(td1)
	err := dir.UpdateThing(agentID, td1Json)

	// 1. Retrieve the TD from the directory.
	dtwList, err := dir.RetrieveAllThings(0, 0)
	require.NoError(t, err)
	require.Equal(t, 1, len(dtwList))
	dtw1, err := td.UnmarshalTD(dtwList[0])
	require.NoError(t, err)

	// 2. The digitwin ID should have the dtw prefix
	assert.True(t, strings.HasPrefix(dtw1.ID, digitwinapi.DigitwinIDPrefix))

	// 3. check if properties, events and actions are still there
	require.Equal(t, len(td1.Properties), len(dtw1.Properties))
	require.Equal(t, len(td1.Events), len(dtw1.Events))
	require.Equal(t, len(td1.Actions), len(dtw1.Actions))

	// 4. check if the base form points to the server
	require.NotEmpty(t, dtw1.Base, "Missing base in TD")
	expectedBase := testEnv.Server.GetConnectURL()
	assert.Equal(t, expectedBase, dtw1.Base)

	// 5. check if the forms in the affordances are replaced
	for _, aff := range dtw1.Properties {
		require.NotEmpty(t, aff.Forms)
		form0 := aff.Forms[0]
		assert.NotEmpty(t, form0.GetOperations())
		subprotocol, _ := form0.GetSubprotocol()
		assert.Equal(t, subprotocol, wss.SubprotocolWotWSS)
	}
	for _, aff := range dtw1.Events {
		require.NotEmpty(t, aff.Forms)
		assert.NotEmpty(t, aff.Forms[0].GetOperations())
	}
	for _, aff := range dtw1.Actions {
		require.NotEmpty(t, aff.Forms)
		assert.NotEmpty(t, aff.Forms[0].GetOperations())
	}

	require.NoError(t, err)
	_ = dtw
}

// Read a property from the digital twin
func TestReadDigitwinProperty(t *testing.T) {
	t.Logf("---%s---\n", t.Name())
	const agentID = "agent1"
	const prop1Name = "prop-0" // generated by test env
	const prop1Value = "value1"
	var thing1ID string

	testEnv, dir, dtw, stopFn := startService()
	_ = dtw
	defer stopFn()

	// the digital twin sink will receive the request for read unknown property
	dtw.SetRequestSink(func(req *msg.RequestMessage, replyTo msg.ResponseHandler) error {
		if req.Operation == wot.OpReadProperty {
			if req.ThingID == thing1ID && req.Name == prop1Name {
				resp := req.CreateResponse(prop1Value, nil)
				err := replyTo(resp)
				return err
			}
		}
		return fmt.Errorf("unknown request ")
	})

	// 1. pretent to be an agent that writes a TD to the directory
	td1 := testEnv.CreateTestTD(0)
	thing1ID = td1.ID
	td1Json, _ := td.MarshalTD(td1)
	err := dir.UpdateThing(agentID, td1Json)
	assert.NoError(t, err)

	// 2. the agent emits a property notification from the thing to the server
	// in the test setup the directory is the first module in the pipeline
	prop1 := td1.Properties[prop1Name]
	assert.NotEmpty(t, prop1)
	ev1 := msg.NewNotificationMessage(agentID, msg.AffordanceTypeProperty,
		thing1ID, prop1Name, prop1Value)
	dir.HandleNotification(ev1)

	// the digital twin module receives this thing notification and updates the digital twin
	// the digital twin in return submits it to subscribers.

	// 3. the consumer reads the property value
	dtwThingID := module.MakeDigitwinID(agentID, thing1ID)
	req1 := msg.NewRequestMessage(wot.OpReadProperty, dtwThingID, prop1Name, nil, "")
	//
	// vcache does not forward the request as the request thingID is that of the digitwin.
	// the digitwin module should forward the request if vcache doesn't have a value.
	// in production it should forward and eventually reach the device itself.
	var respValue string
	err = dir.HandleRequest(req1, func(resp *msg.ResponseMessage) error {
		err2 := resp.Decode(&respValue)
		assert.NoError(t, err2)
		return err2
	})
	require.NoError(t, err)
	assert.Equal(t, prop1Value, respValue)

}
