// Package authn with the agent request handler for using service 'User'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Generated 18 Nov 2025 13:58 PST.
package authnclient

import (
	"github.com/hiveot/hivekit/go/lib/consumer"
	"github.com/hiveot/hivekit/go/modules"
	"github.com/hiveot/hivekit/go/modules/authn"
	"github.com/hiveot/hivekit/go/modules/authn/server"
	"github.com/hiveot/hivekit/go/modules/clients"
	"github.com/hiveot/hivekit/go/wot"
)

// AuthnUserMsgClient is a client for authentication operations using RRN messages
// Intended to be linked to a transport client module for message delivery.
type AuthnUserMsgClient struct {
	modules.HiveModuleBase
	// the authn module providing the actual functionality
	co *clients.Consumer
	// The ThingID of the server to connect to
	authServiceID string
}

// UserGetProfile client method - Get Client Profile.
func (cl *AuthnUserMsgClient) GetProfile() (resp authn.ClientProfile, err error) {
	err = cl.co.Rpc(wot.OpInvokeAction,
		server.AuthnUserServiceID,
		server.UserActionGetProfile, nil, &resp)
	return
}

// // Login with password
// func (cl *AuthnUserMsgClient) Login(clientID string, password string) (token string, err error) {
// 	var args = authn.UserLoginArgs{UserName: clientID, Password: password}
// 	err = cl.cc.Rpc("invokeaction", authn.AuthnUserServiceID, UserLoginAction, &args, &token)
// 	return
// }

// Logout client method - Logout.
// Logout from all devices
func (cl *AuthnUserMsgClient) Logout() (err error) {

	err = cl.co.Rpc(wot.OpInvokeAction,
		server.AuthnUserServiceID,
		server.UserActionLogout, nil, nil)
	return
}

// UserRefreshToken client method - Request a new auth token for the current client.
func (cl *AuthnUserMsgClient) RefreshToken(hc *consumer.Consumer, oldToken string) (newToken string, err error) {

	err = cl.co.Rpc(wot.OpInvokeAction,
		server.AuthnUserServiceID,
		server.UserActionRefreshToken, &oldToken, &newToken)
	return
}

// UserUpdatePassword client method - Update Password.
// Request changing the password of the current client
func (cl *AuthnUserMsgClient) UpdateProfile(hc *consumer.Consumer, password string) (err error) {
	err = cl.co.Rpc(wot.OpInvokeAction,
		server.AuthnUserServiceID,
		server.UserActionSetPassword, &password, nil)
	return
}

func NewAuthnUserMsgClient(co *clients.Consumer) *AuthnUserMsgClient {
	cl := &AuthnUserMsgClient{
		co: co,
	}
	return cl
}
