package internal

import (
	"log/slog"

	"github.com/hiveot/hivekit/go/api"
	"github.com/hiveot/hivekit/go/api/msg"
	"github.com/hiveot/hivekit/go/modules"
	"github.com/teris-io/shortid"
)

// The BusRecipe is a module where members are used in parallel.
//
// Incoming requests are handled in two steps; first the thingID is matched.
// If no match is found then the request is passed to each member in turn until
// it is accepted.
// If no modules accept the request then it is passed to the request sink.
//
// Incoming notifications are passed to each bus member in order of definition.
//
// The bus recipe itself is registered as the notification sink of each member.
//
// Notifications received or generated by member modules are passed to the bus's
// notification sink. If a member forwards a notification that was passed by
// the recipe, it is ignored to prevent duplicate notifications.
//
// The group recipe differs from the star recipe in that the request thingID does
// not have to match the member module's ID. This is useful to send requests to
// modules that represent multiple Things.
type BusRecipe struct {
	modules.HiveModuleBase
	// modules in the order to instantiate and link
	modDefs []api.ModuleDefinition `yaml:"star"`

	// module instances by their ThingID
	instances map[string]api.IHiveModule

	// The factory to use
	f api.IModuleFactory
}

// Receive a notification from a group member.
// if the notification originates from a member then send it up the chain.
// if the notification is simply passed through then ignore it.
func (m *BusRecipe) HandleMemberNotification(notif *msg.NotificationMessage) {

	// how to identify if the notification originated in the group?
	m.ForwardNotification(notif)
}

// Recipe receives notifications from downstream.
// Send it to all modules in the group and then up the chain.
func (m *BusRecipe) HandleNotification(notif *msg.NotificationMessage) {
	for _, member := range m.instances {
		member.HandleNotification(notif)
	}
}

// Requests sent to the group are passed to each module until it succeeds.
// If no modules succeed then pass it down the chain.
func (m *BusRecipe) HandleRequest(req *msg.RequestMessage, replyTo msg.ResponseHandler) error {
	var err error
	for _, member := range m.instances {
		err = member.HandleRequest(req, replyTo)
		if err == nil {
			// request was handled by a group member
			return nil
		}
	}
	return m.ForwardRequest(req, replyTo)
}

// Start the recipe
func (m *BusRecipe) Start() error {

	// add the module definitions to the factory
	if m.modDefs != nil {
		// register all modules
		for _, modDef := range m.modDefs {
			m.f.RegisterModule(modDef)
		}
	}
	// start modules in the defined order and link their notifications
	for _, moduleDef := range m.modDefs {
		instance, err := m.f.StartModule(moduleDef.Type, true)
		// module cant be started. This is fatal
		if err != nil {
			slog.Error("BusRecipe: starting module failed. Shutting down",
				"moduleType", moduleDef.Type, "err", err.Error())
			m.Stop()
			return err
		} else if m == nil {
			// don't track 'one-shot' modules that are used to initialize the factory.
			// These return nil without error.
		} else {
			m.instances[instance.GetThingID()] = instance
			// requests send by the ray will be forwarded to the star, which
			// passes it to the ray module with the matching thingID. See HandleRequest.
			instance.SetRequestSink(m)
			// all notifications from the rays will be forwarded to the star. See HandleNotification.
			instance.SetNotificationSink(m)
		}
	}
	return nil
}

// Create a new bus recipe with an array of modules
func NewBusRecipe(modDefs []api.ModuleDefinition) api.IHiveModule {
	thingID := "BusRecipe-" + shortid.MustGenerate()
	m := &BusRecipe{
		HiveModuleBase: *modules.NewHiveModuleBase(thingID, 0),
		modDefs:        modDefs,
	}
	return m
}
