package internal

import (
	"log/slog"

	"github.com/hiveot/hivekit/go/api"
	"github.com/hiveot/hivekit/go/api/msg"
	"github.com/hiveot/hivekit/go/modules"
	"github.com/teris-io/shortid"
)

// EXPERIMENTAL: USE AT OWN RISK
// The BusRecipe is a module where members are used in parallel.
//
// Incoming requests are handled in two steps; first the thingID is matched.
// If no match is found then the request is passed to each member in turn until
// it is accepted.
// If no modules accept the request then it is passed to the request sink.
//
// Incoming notifications are passed to each bus member in order of definition.
//
// The bus recipe itself is registered as the notification sink of each member.
//
// Notifications received or generated by member modules are passed to the bus's
// notification sink (not the handler). Notifications passed to HandleNotification
// are passed to all members.
//
// The group recipe differs from the star recipe in that the request thingID does
// not have to match the member module's ID. This is useful to send requests to
// modules that represent multiple Things.
type BusRecipe struct {
	modules.HiveModuleBase
	// modules in the order to instantiate and link
	modDefs []api.ModuleDefinition `yaml:"star"`

	// module instances by their ThingID
	instances map[string]api.IHiveModule

	// The factory to use
	f api.IModuleFactory
}

// Receive a notification from a group member.
// if the notification originates from a member then send it up the chain.
// if the notification is simply passed through then ignore it.
func (m *BusRecipe) HandleMemberNotification(notif *msg.NotificationMessage) {

	// FIXME: how to identify if the notification originated in the group?
	// option1:
	//   modules dont forward received notifications
	//   modules only send generated notifications
	//   recipes can forward received notifications
	//
	//   pro: good for a bus and star, not for a chain
	//   con: devices can no longer chain; need a helper to pass to the correct module
	//   con: need support for setting multiple handlers
	//
	// is chaining a useful innate capability for a module?
	// a: server -> logging -> digitwin -> routing -> client    is a useful request chain
	// b: device -> server     no chain needed? server is the notification sink of the device
	// c: RCdevice -> client => server -> router  -> server|client  no chain needed?
	// d: notifications chain end at a digitwin

	// alternative to chaining?
	// in a bus the difference between module generated notifications and forwarded is key
	//
	// option: no chaining; centralized distribution of notifications
	//         problem: how does digitwin modify the notification thingID?
	//         problem: should everyone get all notifications? No
	//         fix: modules subscribe to factory for notifications of interest
	//              pro: matches WoT subscribe
	//              con: creates a dependency on the factory
	//         who produce notifications?
	//           * Things, services
	//         who distribute notifications?
	//           * servers - handles subscription
	//           * authz - blocks notifications (subscriptions?) to consumers based on roles
	//         who consumes notifications - limited by role
	//           * services, consumers
	//
	// option: create a notification distributor module
	//         uses current module API with Handle/Get/SetNotificationSink and Handle/Get/SetRequestSink
	//         !modules no longer forward received notifications to their sink!
	//         recipe manages the distribution
	//           * used by all servers
	//           * used by factory? - no, by recipe instead
	//           * used in Module API? - use SetNotificationSink as-is
	//           * hook for authz
	//
	m.ForwardNotification(notif)
}

// Recipe receives notifications from downstream.
// Send it to all modules in the group and then up the chain.
func (m *BusRecipe) HandleNotification(notif *msg.NotificationMessage) {
	for _, member := range m.instances {
		member.HandleNotification(notif)
	}
	// how to get member notifications?
	//  should modules forward notifications in a bus? its not a chain!
	m.ForwardNotification(notif)
}

// Requests sent to the group are passed to each module until it succeeds.
// If no modules succeed then pass it down the chain.
func (m *BusRecipe) HandleRequest(req *msg.RequestMessage, replyTo msg.ResponseHandler) error {
	var err error
	for _, member := range m.instances {
		err = member.HandleRequest(req, replyTo)
		if err == nil {
			// request was handled by a group member
			return nil
		}
	}
	return m.ForwardRequest(req, replyTo)
}

// Start the recipe
func (m *BusRecipe) Start() error {

	// add the module definitions to the factory
	if m.modDefs != nil {
		// register all modules
		for _, modDef := range m.modDefs {
			m.f.RegisterModule(modDef)
		}
	}
	// start modules in the defined order
	for _, moduleDef := range m.modDefs {
		member, err := m.f.StartModule(moduleDef.Type, true)
		// module cant be started. This is not fatal
		if err != nil {
			slog.Error("BusRecipe: starting module failed. Not fatal but this might not work as expected",
				"moduleType", moduleDef.Type, "err", err.Error())
			// m.Stop()
			// return err
		} else if m == nil {
			// don't track 'one-shot' modules that are used to initialize the factory.
			// These return nil without error.
		} else {
			m.instances[member.GetThingID()] = member
		}
		// the bus receives notifications from all members
		//
		member.SetNotificationSink(m)
	}
	return nil
}

// Create a new bus recipe with an array of modules
func NewBusRecipe(modDefs []api.ModuleDefinition) api.IHiveModule {
	thingID := "BusRecipe-" + shortid.MustGenerate()
	m := &BusRecipe{
		HiveModuleBase: *modules.NewHiveModuleBase(thingID, 0),
		modDefs:        modDefs,
	}
	return m
}
