package internal

import (
	"log/slog"

	"github.com/hiveot/hivekit/go/api"
	"github.com/hiveot/hivekit/go/api/msg"
	"github.com/hiveot/hivekit/go/modules"
	"github.com/teris-io/shortid"
)

// EXPERIMENTAL: USE AT OWN RISK
// The BusRecipe is a module where members operate in parallel.
//
// The primary use-case is to group gateway multiple servers.
//   - Notifications received by servers from connected services and RC devices
//     are passed to the recipe notification sink (not the notification handler).
//   - Notifications passed to the recipe notification handler are passed to all
//     bus members (servers). Bus members MUST not forward unhandled notifications
//     to their local notification sink as this would cause an endless loop.
//   - Requests received by servers from consumers are passed to the recipe request
//     sink (not the request handler).
//   - Requests
//
// Q: should notifications be forwarded http chain style?
//
//	yes: it allows module chaining without additional helpers, just set the sink.
//	       are helpers a deal breaker when not using the factory?
//	yes: it creates a clear sequence in which modules receive notifications
//	yes: it enables intercepting notifications (authz) -> hmm, maybe not
//	no: it is an implicit chain that conflicts with other recipe styles.
//	no: it prevents differentiating between generated and forwarded notifications,
//	no: when operating modules in parallel notifications would multiply.
//
//	-> option1: require a helper to forward notifications (eg a recipe)
//	-> option2: have a switch in module base to disable forwarding
//
//	why chain notifications to begin with? cant they all go to the same handler?
//	-> how else to pass notifications from any module to others in the chain?
//	     yes this needs a helper
//	-> not all received notifications should be passed to all modules... should they?
//	     transport client received notifications ... ok
//	     are there types of notifications that behave differently?
//
// note: seems there is a need to differentiate between generated notifications
// and forwarded notifications in a module. Should these have two different sinks
// or an extra parameter indicating whether the notification is forwarded?
// -> maybe modules should not forward notifications? Instead the recipe decides
//
//	how to pass notifications from members.
//	   problem: does this break digital twin use-cases?
//	            -> not really. subscribes only subscribe to digitwin devices
//	   problem: modules can no longer be chained without a recipe to do it for them.
//	            -> true. It does simplify its use though
//
// Q: should modules forward requests http chain style?
//
//	yes: filtering and authz depend on it
//	problem: how to decide if a module has unhandled requests?
//
// The bus recipe differs from the chain and star recipe in that requests are
// passed to all members until one accepts the request. Members decide for themselves
// whether to handle a request. This lets requests be handled by modules that
// represent multiple things.
//
// Member modules must be fast in identifying if a request is accepted to avoid
// increased latency due to passing a request to each member.
//
// If no modules accept the request then it is passed to the request sink.
//
// Incoming notifications are passed to each bus member in order of definition.
//
// The bus recipe itself is registered as the notification sink of each member.
//
// Notifications received or generated by member modules are passed to the bus's
// notification sink (not the handler). Notifications passed to HandleNotification
// are passed to all members.
type BusRecipe struct {
	modules.HiveModuleBase
	// modules in the order to instantiate and link
	modDefs []api.ModuleDefinition `yaml:"star"`

	// module instances by their ThingID
	instances map[string]api.IHiveModule

	// The factory to use
	f api.IModuleFactory
}

// Receive a notification from a group member.
// if the notification originates from a member then send it up the chain.
// if the notification is simply passed through then ignore it.
func (r *BusRecipe) HandleMemberNotification(notif *msg.NotificationMessage) {

	// FIXME: how to identify if the notification originated in the group?
	// option1:
	//   modules dont forward received notifications
	//   modules only send generated notifications
	//   recipes can forward received notifications
	//
	//   pro: good for a bus and star, not for a chain
	//   con: devices can no longer chain; need a helper to pass to the correct module
	//   con: need support for setting multiple handlers
	//
	// is chaining a useful innate capability for a module?
	// a: server -> logging -> digitwin -> routing -> client    is a useful request chain
	// b: device -> server     no chain needed? server is the notification sink of the device
	// c: RCdevice -> client => server -> router  -> server|client  no chain needed?
	// d: notifications chain end at a digitwin

	// alternative to chaining?
	// in a bus the difference between module generated notifications and forwarded is key
	//
	// option: no chaining; centralized distribution of notifications
	//         problem: how does digitwin modify the notification thingID?
	//         problem: should everyone get all notifications? No
	//         fix: modules subscribe to factory for notifications of interest
	//              pro: matches WoT subscribe
	//              con: creates a dependency on the factory
	//         who produce notifications?
	//           * Things, services
	//         who distribute notifications?
	//           * servers - handles subscription
	//           * authz - blocks notifications (subscriptions?) to consumers based on roles
	//         who consumes notifications - limited by role
	//           * services, consumers
	//
	// option: create a notification distributor module
	//         uses current module API with Handle/Get/SetNotificationSink and Handle/Get/SetRequestSink
	//         !modules no longer forward received notifications to their sink!
	//         recipe manages the distribution
	//           * used by all servers
	//           * used by factory? - no, by recipe instead
	//           * used in Module API? - use SetNotificationSink as-is
	//           * hook for authz
	//
	r.ForwardNotification(notif)
}

// Recipe receives notifications from downstream.
// Send it to all modules in the group and then up the chain.
func (r *BusRecipe) HandleNotification(notif *msg.NotificationMessage) {
	for _, member := range r.instances {
		member.HandleNotification(notif)
	}
	// how to get member notifications?
	//  should modules forward notifications in a bus? its not a chain!
	r.ForwardNotification(notif)
}

// Requests sent to the group are passed to each module until it succeeds.
// If no modules succeed then pass it down the chain.
func (r *BusRecipe) HandleRequest(req *msg.RequestMessage, replyTo msg.ResponseHandler) error {
	var err error
	for _, member := range r.instances {
		err = member.HandleRequest(req, replyTo)
		if err == nil {
			// request was handled by a group member
			return nil
		}
	}
	return r.ForwardRequest(req, replyTo)
}

// Start the recipe
func (r *BusRecipe) Start() error {

	// add the module definitions to the factory
	if r.modDefs != nil {
		// register all modules
		for _, modDef := range r.modDefs {
			r.f.RegisterModule(modDef)
		}
	}
	// start modules in the defined order
	for _, moduleDef := range r.modDefs {
		member, err := r.f.StartModule(moduleDef.Type, true)
		// module cant be started. This is not fatal
		if err != nil {
			slog.Error("BusRecipe: starting module failed. Not fatal but this might not work as expected",
				"moduleType", moduleDef.Type, "err", err.Error())
			// m.Stop()
			// return err
		} else if r == nil {
			// don't track 'one-shot' modules that are used to initialize the factory.
			// These return nil without error.
		} else {
			r.instances[member.GetThingID()] = member
		}
		// the bus receives notifications from all members
		//
		member.SetNotificationSink(r)
	}
	return nil
}

// Create a new bus recipe with an array of modules
func NewBusRecipe(modDefs []api.ModuleDefinition) api.IHiveModule {
	thingID := "BusRecipe-" + shortid.MustGenerate()
	m := &BusRecipe{
		HiveModuleBase: *modules.NewHiveModuleBase(thingID, 0),
		modDefs:        modDefs,
	}
	return m
}
